### ISSUE TITLE
It returns message "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by phamxtien** [dsdanielpark/Gemini-API#19] opened 2024-03-11 22:44 UTC
**Describe the bug**
Gemini returns message "maximum recursion depth exceeded"

**Version**
OS: Ubuntu 23.10
Python: 3.11
Gemini API: 2.0.0
Using proxy: None
Legion:

**Code**
```python
from gemini import Gemini

cookies = {} # I input my cookies here as decribe in README
GeminiClient = Gemini(cookies=cookies)

prompt = "hello, how are you?"
response = GeminiClient.generate_content(prompt)

print(response.response.dict)
```

**Error**
```
It returns "maximum recursion depth exceeded"
I check on gemini.google.com/app, 
it has sent prompt to gemini but not get answer from gemini.google.com/app as below image 
Bard API still runs smooth!
```
![image](https://github.com/dsdanielpark/Gemini-API/assets/33739597/94babaaa-3b07-4bff-b24c-88fcd3fb5445)

**Comment by dsdanielpark** [comment] 2024-03-12 12:00
Thank you for reporting.

Please give me tracebacked error message.

**Comment by cacko** [comment] 2024-03-14 06:06
looks like it returns attachment instead of text now, response.bin, dunno have not dig much, so sorry if that makes no sense

**Comment by dsdanielpark** [comment] 2024-03-14 15:48
Would it still work if I leave the Gemini object as is and only rerun the generate content method? I'll check again tomorrow. I was aware of the bot server change, but since the old bot server was still running, I didn't make the switch, though I'm a bit scared, I'll check it again.

Before posting it on the readme, I'll first post it on this issue page. Since it's difficult to code and check, I'll get back to you within 12 hours!

Thank you.

**Comment by PushkarOP** [comment] 2024-03-15 03:57
Traceback (most recent call last):
  File "c:\Users\Divyanshi\Desktop\New\tets.py", line 83, in <module>
    print(geminiultra("What is the capital of France? also show images"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Divyanshi\Desktop\New\tets.py", line 45, in geminiultra
    answer = response.response_dict['candidates']['text']
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyanshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gemini\src\model\output.py", line 47, in response_dict
    return self.response_dict
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyanshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gemini\src\model\output.py", line 47, in response_dict
    return self.response_dict
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Divyanshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gemini\src\model\output.py", line 47, in response_dict
    return self.response_dict
           ^^^^^^^^^^^^^^^^^^
  [Previous line repeated 995 more times]
RecursionError: maximum recursion depth exceeded

**Comment by dsdanielpark** [comment] 2024-03-15 04:10
Thank you for reporting. I will check this issue ASAP.

**Comment by phamxtien** [comment] 2024-03-17 11:11
I just update to Ver 2.2.0 and it still returns "maximum recursion depth exceeded"

**Comment by dsdanielpark** [comment] 2024-03-17 11:32
[phamxtien](https://github.com/phamxtien)
The update in Python 3.11 is suspected to cause recursive calls leading to a "recursive exceed" error.

I've made modifications to change the recursive calls in property definitions in GeminiModelOutput. Could you please reinstall the version from GitHub and check again?
```
pip install git+https://github.com/dsdanielpark/Gemini-API.git
```

**Comment by phamxtien** [comment] 2024-03-17 12:39
Thank you for your guide
I just get newest source and it still return the same error
I will try with python3 3.8

**Comment by dsdanielpark** [comment] 2024-03-17 13:56
Are you sure to use `print(response.response_dict)` ?

Or try to use `rint(response.payload)`

It seems the issue is related to a property, which might confuse other users. I'm concerned but will fix it as soon as possible. Please keep following the issue for updates; I'll correct it soon and adjust the settings to address the error. In reality, there's still a lot to refactor and implement, but due to a busy schedule, I haven't been able to devote much time to it. Thank you.

**Comment by phamxtien** [comment] 2024-03-17 14:28
> use `print(response.response_dict)` ?

I use print(response.response_dict)

**Comment by dsdanielpark** [comment] 2024-03-18 04:59
[phamxtien](https://github.com/phamxtien)

I release `v2.2.2`. Could you check?

**Comment by Nexusaitemp** [comment] 2024-03-18 15:22
> rint(response.payload)

it works, and response format is also changed

```
{'metadata': ['c_37bce86328f5eb0c', 'r_7ad361e5f2e31296'], 'prompt_class': None, 'prompt_candidates': [], 'candidates': [{'rcid': 'rc_dcc7ef3199425605', 'text': 'The capital of France is Paris. It is a major European city and a global center for art, fashion, gastronomy, and culture. \n[Image of Paris, France] ', 'code': {}, 'web_images': [{'url': 'https://sa.visamiddleeast.com/dam/VCOM/regional/cemea/generic-cemea/travel-with-visa/destinations/paris/marquee-travel-paris-800x450.jpg', 'title': '[Image of Paris, France]', 'alt': 'Paris, France'}], 'generated_images': []}, {'rcid': 'rc_af89988c3898dec1', 'text': 'The capital of France is Paris.  Paris is a major world center for art, fashion, cuisine, and culture.   \n[Image of Paris, France]', 'code': {}, 'web_images': [{'url': 'https://sa.visamiddleeast.com/dam/VCOM/regional/cemea/generic-cemea/travel-with-visa/destinations/paris/marquee-travel-paris-800x450.jpg', 'title': '[Image of 
Paris, France]', 'alt': 'Paris, France'}], 'generated_images': []}, {'rcid': 'rc_daf9c135dc80150a', 'text': "The capital of France is Paris. It's a major European city and a global center for art, fashion, gastronomy, and culture. \n[Image of Paris, France]", 'code': {}, 'web_images': [{'url': 'https://sa.visamiddleeast.com/dam/VCOM/regional/cemea/generic-cemea/travel-with-visa/destinations/paris/marquee-travel-paris-800x450.jpg', 'title': '[Image of Paris, France]', 'alt': 'Paris, France'}], 'generated_images': []}]}
```

**Comment by phamxtien** [comment] 2024-03-19 23:23
> [phamxtien](https://github.com/phamxtien)
> 
> I release `v2.2.2`. Could you check?

Thanks, it runs smooth

**Comment by dsdanielpark** [comment] 2024-03-20 06:46
Thank you for reporting! Have a nice day. I will close this issue as complet.

**Closed by dsdanielpark** 2024-03-20 06:46 UTC
Labels: bug, inprogress
